
import = ["/home/kali/.config/alacritty/themes/themes/github_dark_tritanopia.toml"]

[font]
size = 9.6

[font.normal]
family = "Jetbrains Mono"

[window]
opacity = 0.9
padding =  {x=15,y=15}

[window.dimensions]
columns = 180
lines = 56

